# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runDPMUnc <- function(observedData, observedVars, totalIterations, thinningFreq, quiet, saveClusterParams, saveLatentObs, outputDir, clusterAllocations, kappa0, alpha0, beta0) {
    invisible(.Call(`_DPMUnc_runDPMUnc`, observedData, observedVars, totalIterations, thinningFreq, quiet, saveClusterParams, saveLatentObs, outputDir, clusterAllocations, kappa0, alpha0, beta0))
}

resumeDPMUnc <- function(observedData, observedVars, remainingIterations, thinningFreq, quiet, saveClusterParams, saveLatentObs, outputDir, clusterAllocations, latentObservations, alpha_concentration, kappa0, alpha0, beta0) {
    invisible(.Call(`_DPMUnc_resumeDPMUnc`, observedData, observedVars, remainingIterations, thinningFreq, quiet, saveClusterParams, saveLatentObs, outputDir, clusterAllocations, latentObservations, alpha_concentration, kappa0, alpha0, beta0))
}

